<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8f020a1068656c6c6f776f726c642e70726f746f120a68656c6c6f776f" .
            "726c64221c0a0c48656c6c6f52657175657374120c0a046e616d65180120" .
            "012809221d0a0a48656c6c6f5265706c79120f0a076d6573736167651801" .
            "20012809324b0a094d7947726565746572123e0a0853617948656c6c6f12" .
            "182e68656c6c6f776f726c642e48656c6c6f526571756573741a162e6865" .
            "6c6c6f776f726c642e48656c6c6f5265706c792200425d0a48696f2e6772" .
            "70632e6d792e62616964752e686973746f72792e7265736f7572652e636f" .
            "6d6d69742e70726f746f2e686973746f72792e7265736f7572652e68656c" .
            "6c6f776f726c64420f48656c6c6f576f726c6450726f746f500162067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

